schemaVersion: 2.1.0
metadata:
  name: devworkspace-telemetry-woopra-plugin
  version: 0.0.1
  description: Telemetry plugin for sending information to Woopra
  displayName: Woopra Telemetry Plugin
components:
  - name: devworkspace-telemetry-woopra-plugin
    attributes:
      app.kubernetes.io/component: telemetry
      app.kubernetes.io/part-of: che-theia.eclipse.org
      workspaceEnv:
        - name: DEVWORKSPACE_TELEMETRY_BACKEND_PORT
          value: '4167'
    container:
      image: quay.io/eclipse/devworkspace-telemetry-woopra-plugin:latest
      env:
        - name: WOOPRA_DOMAIN
          value: $WOOPRA_DOMAIN
        - name: SEGMENT_WRITE_KEY
          value: $SEGMENT_WRITE_KEY
