name: amplitude-plugin PR check

env:
  ORGANIZATION: 'eclipse'
  TAG: 'pr-check'

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          ./mvnw --settings settings.xml clean verify -Dnative -Dquarkus.native.container-build=true -DskipTests
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      - name: Build image
        run: |
          docker build -t quay.io/${ORGANIZATION}/devworkspace-telemetry-amplitude-plugin:${TAG} -f src/main/docker/Dockerfile.native .
